// Proposals
export const FETCH_PROPOSALS = 'FETCH_PROPOSALS';

// User
export const CONNECT_USER = 'CONNECT_USER';
export const DISCONNECT_USER = 'DISCONNECT_USER';
export const SET_DAI_DEPOSIT = 'SET_DAI_DEPOSIT';
export const SET_DAI_BALANCE = 'SET_DAI_BALANCE';
export const SET_DAI_ALLOWANCE = 'SET_DAI_ALLOWANCE';
export const SET_HAS_A_PROPOSAL = 'SET_HAS_A_PROPOSAL';
export const SET_ENABLED_TWITTER = 'SET_ENABLED_TWITTER';

// Fund
export const SET_INTEREST_PREV = 'SET_INTEREST_PREV';
export const SET_INTEREST_NEXT = 'SET_INTEREST_NEXT';
export const SET_FUND_SIZE = 'SET_FUND_SIZE';

//web3
export const SET_PROVIDER = 'SET_PROVIDER';
export const SET_NETWORK_INFO = 'SET_NETWORK_INFO';
